name: Notify on Action

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: www.gmail.com  # Replace with your SMTP server
          server_port: 587                   # Common port for SMTP
          username: ${{ secrets.CypressFramework }}  # Your email username
          password: ${{ secrets.9545tyui@# }}  # Your email password
          subject: 'GitHub Action Triggered'  # Subject of the email
          body: 'A GitHub Action was triggered on the main branch.'  # Email body
          to: ubhedaladinath04@gmail.com            # Recipient's email address
          from: ubhedaladinath111@gmail.com              # Sender's email address
