name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          server_address: www.gmail.com  # Replace with your SMTP server
          server_port: 465                  # Common port for SMTP
          username: ${{ secrets.CypressFramework }}  # Your email username
          password: ${{ secrets.CypressFrameworkPassword }}  # Your email password
          subject: 'GitHub Action Triggered'  # Subject of the email
          body: 'A GitHub Action was triggered on the main branch.'  # Email body
          to: ubhedaladinath04@gmail.com            # Recipient's email address
          from: ubhedaladinath111@gmail.com              # Sender's email address
        